package com.review.domain;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;

@Document(collection="Reviews")
@Data
public class Review {

    /**
     * The ID , or Primary key, of the review , as generated by MongoDB
     *
     */
    @Id
    private String id;

    /**
     * The product Id for which the review is applicable
     *
     */
    private Integer productId;

    /**
     * The version of the review which is an increasing number starting with 1
     */
    private Integer  version =1;

    /**
     * A list of review entries - these contain user reviews of the product
     */
    private List<ReviewEntry> entries = new ArrayList<>();

    public Review() {

    }

    public Review(Integer productId) {
        this.productId = productId;
    }

    public Review(String id, Integer productId) {
        this.id = id;
        this.productId = productId;
    }

    public Review(String id, Integer productId, Integer version) {
        this.id = id;
        this.productId = productId;
        this.version = version;
    }

}
